version: 0.2

env:
  variables:
    SOLUTION: .\CSharpHelloWorld.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2

phases:
  install:
    runtime-versions:
        dotnet: 2.2
 artifacts:
  files:
    - .\CSharpHelloWorld\bin\Debug\*
